# Theme
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "default"

# Site Settings
locale: "tr-TR"
title: "Gülce Gök Hukuk Yazıları"
title_separator: "-"
description: "Hukuk üzerine sade ve anlaşılır yazılar"
name: "Gülce Gök"
url: ""
baseurl: ""
repository: ""
masthead_title: ""
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true
copyright: "Gülce Gök"

# Author
author:
  name: "Gülce Gök"
  bio: "Hukuk üzerine yazılar ve yorumlar."
  location: "Türkiye"
  avatar: ""
  email: ""
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GulceGok"

# Footer
footer:
  since: "2025"
  links: []

# Posts
paginate: 5
pagination:
  per_page: 10
  sort_reverse: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Markdown
markdown: kramdown
kramdown:
  input: GFM

